[Icon Theme]
Name=KnoxOS
Comment=Default icon theme for KnoxOS
Inherits=hicolor
Directories=apps,devices,places,mimetypes,categories,status,actions,emblems,panel,animations

[apps]
Size=scalable
MinSize=16
MaxSize=512
Type=Scalable
Context=Applications

[devices]
Size=scalable
MinSize=16
MaxSize=512
Type=Scalable
Context=Devices

[places]
Size=scalable
MinSize=16
MaxSize=512
Type=Scalable
Context=Places

[mimetypes]
Size=scalable
MinSize=16
MaxSize=512
Type=Scalable
Context=MimeTypes

[categories]
Size=scalable
MinSize=16
MaxSize=512
Type=Scalable
Context=Categories

[status]
Size=scalable
MinSize=16
MaxSize=512
Type=Scalable
Context=Status

[actions]
Size=16
Type=Fixed
Context=Actions

[emblems]
Size=scalable
MinSize=16
MaxSize=512
Type=Scalable
Context=Emblems

[panel]
Size=24
Type=Fixed
Context=Panel

[animations]
Size=scalable
MinSize=16
MaxSize=512
Type=Scalable
Context=Animations
