/// UI Widgets — reusable retained-mode GUI components.
mod avatar;
mod badge;
mod banner;
mod button;
mod chart;
mod checkbox;
mod code_editor;
mod context_menu;
mod date_time;
mod file_picker;
mod pagination;
mod progress_bar;
mod radio;
mod rating;
mod rich_text;
mod scroll_bar;
mod separator;
mod slider;
mod stepper;
mod tab_bar;
mod tag_input;
mod text_input;
mod toggle;
mod tooltip;
mod util;
mod video_player;

pub use avatar::AvatarWidget;
pub use badge::Badge;
pub use banner::{BannerType, NotificationBanner};
pub use button::Button;
pub use chart::{Chart, ChartSeries, ChartType};
pub use checkbox::Checkbox;
pub use code_editor::{CodeEditor, SyntaxLanguage};
pub use context_menu::{ContextMenu, MenuItem};
pub use date_time::DateTimePicker;
pub use file_picker::{FilePickerDialog, FilePickerEntry, FilePickerMode};
pub use pagination::PaginationWidget;
pub use progress_bar::ProgressBar;
pub use radio::{RadioButton, RadioGroup};
pub use rating::RatingWidget;
pub use rich_text::{RichSpan, RichTextEditor, RichTextStyle};
pub use scroll_bar::ScrollBar;
pub use separator::Separator;
pub use slider::Slider;
pub use stepper::StepperWidget;
pub use tab_bar::TabBar;
pub use tag_input::TagInput;
pub use text_input::TextInput;
pub use toggle::ToggleSwitch;
pub use tooltip::Tooltip;
pub use video_player::{PlaybackState, VideoPlayer};
