#!/usr/bin/env python3
"""
Generate HD (20×40) antialiased Hack font glyph data for KnoxOS kernel.

Rasterizes Hack-Regular.ttf at a large size into a 20×40 cell with full 8-bit
alpha coverage per pixel.  This gives 4× the detail of the standard 10×20 font,
making text crisp even at scale 2 (which produces the same visual size as the
old scale-4-from-10×20 but with dramatically better quality).

Output: kernel/src/gui/hack_font_hd.rs
"""

from PIL import Image, ImageDraw, ImageFont
import os, sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# Try multiple TTF locations
TTF_CANDIDATES = [
    os.path.join(SCRIPT_DIR, "..", "egui", "crates", "epaint_default_fonts", "fonts", "Hack-Regular.ttf"),
    os.path.join(SCRIPT_DIR, "..", "hack", "build", "ttf", "Hack-Regular.ttf"),
]
OUTPUT_PATH = os.path.join(SCRIPT_DIR, "..", "kernel", "src", "gui", "hack_font_hd.rs")

GLYPH_WIDTH = 20
GLYPH_HEIGHT = 40
FIRST_CHAR = 0x20
LAST_CHAR = 0x7E
GLYPH_COUNT = LAST_CHAR - FIRST_CHAR + 1

# Supersample factor for smoother AA edges
SUPERSAMPLE = 4


def find_ttf():
    for p in TTF_CANDIDATES:
        if os.path.isfile(p):
            return p
    print("ERROR: Hack-Regular.ttf not found in any of:", TTF_CANDIDATES, file=sys.stderr)
    sys.exit(1)


def rasterize_glyphs(ttf_path):
    """Rasterize all printable ASCII as 20×40 alpha-coverage maps.

    Strategy: render at SUPERSAMPLE× resolution (80×160), then box-downsample
    to 20×40.  This gives exact area-coverage AA — the same technique used by
    FreeType's auto-hinter and macOS Core Text.
    """
    ss = SUPERSAMPLE
    ss_w, ss_h = GLYPH_WIDTH * ss, GLYPH_HEIGHT * ss  # 80×160

    # Find the right font size so that glyphs fit in the cell
    # Target: ascender + descender fills ~80% of cell height (leaving padding)
    best_size = 28
    for try_size in range(36, 16, -1):
        font = ImageFont.truetype(ttf_path, try_size * ss)
        asc, desc = font.getmetrics()
        # Check if total height fits in cell (with some padding)
        if (asc + desc) <= ss_h - (2 * ss):
            best_size = try_size
            break

    font = ImageFont.truetype(ttf_path, best_size * ss)
    asc, desc = font.getmetrics()
    total_height = asc + desc

    print(f"Font size: {best_size} (SS: {best_size * ss}), metrics: asc={asc} desc={desc} total={total_height}")
    print(f"Cell: {GLYPH_WIDTH}×{GLYPH_HEIGHT}, supersample: {ss_w}×{ss_h}")

    glyphs = []

    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        ch = chr(code)

        # Render at supersample resolution
        img = Image.new('L', (ss_w, ss_h), 0)

        if ch != ' ':
            draw = ImageDraw.Draw(img)
            bbox = font.getbbox(ch)
            gw = bbox[2] - bbox[0]
            gh = bbox[3] - bbox[1]

            # Center horizontally
            x_off = (ss_w - gw) // 2 - bbox[0]
            # Baseline: place ascender portion in upper 80% of cell
            # padding_top = 3 pixels at target resolution = 3*ss at SS resolution
            padding_top = 3 * ss
            y_off = padding_top - bbox[1]  # bbox[1] is the top offset (usually negative from baseline)

            draw.text((x_off, y_off), ch, fill=255, font=font)

        # Box-downsample to target resolution
        # Each target pixel = average of ss×ss source pixels → exact area coverage
        coverage = []
        for ty in range(GLYPH_HEIGHT):
            row = []
            for tx in range(GLYPH_WIDTH):
                total = 0
                for sy in range(ss):
                    for sx in range(ss):
                        total += img.getpixel((tx * ss + sx, ty * ss + sy))
                avg = total // (ss * ss)
                row.append(avg)
            coverage.append(row)

        glyphs.append((code, ch, coverage))

    return glyphs


def write_rust(glyphs):
    """Write hack_font_hd.rs with the HD glyph data."""
    lines = []
    lines.append('/// Hack HD Antialiased Font — 20×40 high-resolution glyph data for KnoxOS')
    lines.append('///')
    lines.append('/// Each pixel is an 8-bit alpha coverage value (0=transparent, 255=opaque).')
    lines.append('/// Generated by rasterizing Hack-Regular.ttf at 4× supersample resolution')
    lines.append('/// then box-downsampling for exact area-coverage antialiasing.')
    lines.append('///')
    lines.append('///   HD: 20×40 pixels (used for scale ≥ 2, giving 4× the detail of 10×20)')
    lines.append('')
    lines.append(f'pub const GLYPH_WIDTH_HD: usize = {GLYPH_WIDTH};')
    lines.append(f'pub const GLYPH_HEIGHT_HD: usize = {GLYPH_HEIGHT};')
    lines.append('')
    lines.append('pub fn get_glyph_hd(ch: char) -> Option<&\'static [[u8; GLYPH_WIDTH_HD]; GLYPH_HEIGHT_HD]> {')
    lines.append('    let idx = ch as usize;')
    lines.append('    if idx >= 0x20 && idx <= 0x7E {')
    lines.append('        Some(&HACK_AA_HD[idx - 0x20])')
    lines.append('    } else {')
    lines.append('        None')
    lines.append('    }')
    lines.append('}')
    lines.append('')
    lines.append('#[rustfmt::skip]')
    lines.append(f'static HACK_AA_HD: [[[u8; GLYPH_WIDTH_HD]; GLYPH_HEIGHT_HD]; {GLYPH_COUNT}] = [')

    for code, ch, coverage in glyphs:
        if ch == '\\':
            display = '\\\\'
        elif ch == "'":
            display = "\\'"
        else:
            display = ch
        lines.append(f'    // 0x{code:02X} \'{display}\'')
        lines.append('    [')
        for row in coverage:
            hex_vals = ', '.join(f'0x{v:02X}' for v in row)
            lines.append(f'        [{hex_vals}],')
        lines.append('    ],')

    lines.append('];')
    lines.append('')

    with open(OUTPUT_PATH, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Written {len(glyphs)} HD glyphs ({GLYPH_WIDTH}×{GLYPH_HEIGHT}) to {OUTPUT_PATH}")


def main():
    ttf_path = find_ttf()
    print(f"Using TTF: {ttf_path}")

    glyphs = rasterize_glyphs(ttf_path)

    # Quick sanity: print a few characters as ASCII art
    for code, ch, cov in glyphs:
        if ch in ('K', 'O', 'g', 'y'):
            print(f"\n--- '{ch}' (0x{code:02X}) ---")
            for row in cov:
                line = ''
                for v in row:
                    if v > 200: line += '█'
                    elif v > 150: line += '▓'
                    elif v > 100: line += '▒'
                    elif v > 50: line += '░'
                    elif v > 10: line += '·'
                    else: line += ' '
                print(line)

    write_rust(glyphs)


if __name__ == '__main__':
    main()
